In [25]:
import pandas as pd

schools = pd.read_csv("schools.csv")

schools.head()

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [26]:
filtered_schools = schools[schools["average_math"] >= 0.8*800]

best_math_schools = filtered_schools[["school_name", "average_math"]].sort_values("average_math", ascending=False)

In [27]:
schools["total_SAT"]= schools["average_reading"]+schools["average_writing"]+schools["average_math"]

top_10_schools = schools[["school_name","total_SAT"]].sort_values("total_SAT",ascending=False).head(10)

In [ ]:
borough_stats = schools.groupby("borough")["total_SAT"].agg(["count", "mean", "std"]).round(2)

borough_stats = borough_stats.rename(columns={
    "count": "num_schools", 
    "mean": "average_SAT", 
    "std": "std_SAT"
})

largest_std_dev = borough_stats[borough_stats["std_SAT"] == borough_stats["std_SAT"].max()]

largest_std_dev = largest_std_dev.reset_index()

largest_std_dev

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29